### PR TITLE
Add support page

### PR DESCRIPTION
**Pull request by ppacher**

### CODE REVIEW

**Review by davegson — CHANGES_REQUESTED** [review]
### Questions

- Can I have a mailto: link for one additional resources card as I added in my commits?
- Can one sort the related tickets by "open" first? And after the matching "open" issues show the closed ones?
- Should we add the compatibility report too?

### Feedback & Areas for Improvement

#### Resource Heavy When Title is Long

Small fyi: the longer I write the title the more resources the search process eats, slowed down my computer quite a bit

#### If You Leave the Page And All Is Forgotten

When entering a bug report and then going to the "how did I reproduce it?" I am invited to go away from that form and to retry the bug. However, if I do so and come back **all my texts will have disappeared**. This really sucks from a UX perspective. Can't we save the texts that already were entered? Otherwise this will lead to super frustrating experiences.

#### Log Levels

We show the disclaimer that ppl should check the logs, is there not a way to maybe exclude all sensitive information automatically? Would make the job clearer & easier.

#### Input Fields

Inputs should have labels above the input field, so after one already starts entering stuff one still remembers what I should be entering. Especially after filling out the 3 big ones I might have forgotten what the first "big field" was meant to describe.

1. **Label**: Title, **Placeholder**: Summarize the Bug/Improvement
2. **Label**: "What happened?", **Placeholder**: "Describe what happened in detail"
3. **Label**: "What did you expect to happen?", **Placeholder**: "Describe what you expected to happen instead"
4. **Label**: "How did you reproduce it?", **Placeholder**: "Describe how to reproduce the issue"
5. **Label**: "Additional information" (instead of What did we miss?), **Placeholder**: "Provide extra details if needed"

**Comment by davegson** [comment]
oh yeah, forgot to mention - overall amazing work! 🔥 Super pumped for this 🎉😁

**Comment by ppacher** [comment]
> ### Questions
> * Can I have a mailto: link for one additional resources card as I added in my commits?

That should work as it is right now. Did you test your mailto:?

> * Can one sort the related tickets by "open" first? And after the matching "open" issues show the closed ones?

@LukeSeers, any idea of how that filtering could look like?

> * Should we add the compatibility report too?

I guess I just forgot about it ...

> 
> ### Feedback & Areas for Improvement
> #### Resource Heavy When Title is Long
> Small fyi: the longer I write the title the more resources the search process eats, slowed down my computer quite a bit

Good point! Not sure if there's an easy way to do that since we use fuse.js for searching. Though, I can probably increase the debounce time factor to limit the amout of searches done. Will check that.

> 
> #### If You Leave the Page And All Is Forgotten
> When entering a bug report and then going to the "how did I reproduce it?" I am invited to go away from that form and to retry the bug. However, if I do so and come back **all my texts will have disappeared**. This really sucks from a UX perspective. Can't we save the texts that already were entered? Otherwise this will lead to super frustrating experiences.

Another good point! I guess storing the input in a session-local storage (i.e. being lost when the app window is closed) is fine? 

> 
> #### Log Levels
> We show the disclaimer that ppl should check the logs, is there not a way to maybe exclude all sensitive information automatically? Would make the job clearer & easier.

Not sure this is feasible **now** as a lot of information might be considered private and doing this correctly might result in a lot of work! Pinging @dhaavi here for reference. 

> 
> #### Input Fields
> Inputs should have labels above the input field, so after one already starts entering stuff one still remembers what I should be entering. Especially after filling out the 3 big ones I might have forgotten what the first "big field" was meant to describe.

Try adding a [help text]( https://github.com/safing/portmaster-ui/blob/feature/supportpage/modules/portmaster/src/app/pages/support/pages.ts#L8) like [here](https://github.com/safing/portmaster-ui/blob/feature/supportpage/modules/portmaster/src/app/pages/support/pages.ts#L44). That should appear right below the input box. Is that enough for your usecase? If not, @LukeSeers can likely come up with a design for this as well.

>  oh yeah, forgot to mention - overall amazing work! :fire: Super pumped for this :tada: :grin:

Nice to hear! Looking forward to get this (and #160 ) released!

**Comment by davegson** [comment]
I just pushed my fixes and it is ready from my side. There are three likely discussion points which I'd like to get your feedback:

@ppacher:

- I [set a default for the repo](https://github.com/safing/portmaster-ui/pull/156/commits/01b3024a9c4df88cb0ca029a75ed6a5ba00b0fb2) - reasoning is in there too. Would you agree with this strategy as well as its implementation? Feel free to improve this
- I linked to our Pastebin Server from the "Included Debug Logs" paragraph which I think might assert people in the process. I am unsure however if this has drawbacks from a security pov. Thoughts?

@luke: (when you get the time)

- I emojified the big 4 tiles to (a) make it more of an eye-catcher and (b) to unify the process with how it is set up [when creating issues on GitHub](https://github.com/safing/portmaster/issues/new/choose). I know you are not a fan of emojis - but thought this was good UX which is more important than UI.

**Review by davegson — APPROVED** [review]

**Comment by ppacher** [comment]
> * I [set a default for the repo](https://github.com/safing/portmaster-ui/pull/156/commits/01b3024a9c4df88cb0ca029a75ed6a5ba00b0fb2) - reasoning is in there too. Would you agree with this strategy as well as its implementation? Feel free to improve this

I'm fine with it!

> * I linked to our Pastebin Server from the "Included Debug Logs" paragraph which I think might assert people in the process. I am unsure however if this has drawbacks from a security pov. Thoughts?

I guess it's not an issue if we point to the private-bin server but I'm not sure if there are any legal implications of hosting a "public" private-bin instance.

**Comment by davegson** [comment]
> I guess it's not an issue if we point to the private-bin server but I'm not sure if there are any legal implications of hosting a "public" private-bin instance.

I reverted the last commit - can easily rethink this at a later point. Think it is also fine without the link

**Review by davegson — APPROVED** [review]

**Pull request merged**
