### PR TITLE
Autoupdating Dashboard

### PR DESCRIPTION
**Pull request by SammCheese**
Its far more advantageous for a firewall to have close to real-time informations available as described in #434. This PR aims to implement that.
Currently, it updates the Dashboard every 5 seconds with the option to toggle the auto refresh to select and look through entries.

Preview Attached.

https://user-images.githubusercontent.com/52699291/235471520-eeec360a-6db9-422b-a17d-2a5eb0e9ae83.mp4

### CODE REVIEW

**Comment by SammCheese** [comment]
This appears to cause a memory leak somewhere, i'll have to look at this a bit closer. My current suspicions lie on the paginator.

**Comment by dhaavi** [comment]
Hey @SammCheese, thanks for the PR! Great that you want to push things forward here.

However, it is always better to discuss changes beforehand. Someone mentioned that there was some discussion on Discord, but discussion should be finished and changes finalized before proceeding.

In order to take things from here, I suggest taking a two-step approach:

1. First, let's take a step back and collect the requirements for a auto-refresh feature in the network activity view. Then, let's specify how we can fulfill these requirements.
2. After the specification is done and the PR is updated for them, we can start the code review, where we check the code quality and maintainability before we merge this into develop to queue it for release.

Is that approach okay for you?

---

In case it is, let me give you the main issue we've had when specifying auto-refresh: We absolutely do not want to interrupt the user when investigating connections are change the layout while the user is trying to click/select a connection. How can we prevent these things from happening? Which controls does the user need for this and how can we automatically detect these cases?

One inspiration here might be how Grafana is doing this with their auto-updating dashboards. Maybe we could investigate deeper how Grafana handles our concerns and what they do to smooth out UX here.

image

**Comment by SammCheese** [comment]
My idea to prevent it from interrupting users would be to pause the auto update as soon as an accordion is opened, and continue polling once it's closed again. Would that be enough to deal with the Problem?

Regarding Grafana. The design decision to only have a Toggle for auto-updating instead of a whole time select Menu was for simplicity sake. When a users wants to pause the polling to look at a connection, they most likely don't want to scroll through dozens of options. Though I agree that a way to change the Polling speed might be a good idea.

**Comment by SammCheese** [comment]
I've settled with a toggle button and a polling speed selector. Additionally, the polling will now pause when you open an accordion and resume polling when you close it. Also, I've found a Memory Leak, which I've fixed in this PR.

image

**Comment by Raphty** [comment]
Link to contributor discussion on Discord:
https://discord.com/channels/389815143711637517/1105112766227959858

**Comment by LoganDark** [comment]
IMO this is the most incorrect possible way to implement this. When the core has been running for a long time, the latency gets far too high for refreshing the *entire list* periodically to be viable. This should really be updated *incrementally*, either through an event stream or through only fetching new events that happened since the last fetch

**Comment by SammCheese** [comment]
> IMO this is the most incorrect possible way to implement this. When the core has been running for a long time, the latency gets far too high for refreshing the *entire list* periodically to be viable. This should really be updated *incrementally*, either through an event stream or through only fetching new events that happened since the last fetch

You're raising a good point. I was looking for the simplest solution possible. I'll try to rework this to be more on-par in the following days.

**Pull request closed without merging**
