### PR TITLE
Update global and app settings style including various improvements

### PR DESCRIPTION
**Pull request by ppacher**

### CODE REVIEW

**Review by dhaavi — CHANGES_REQUESTED** [review]
First glance:

- Technical:
  - Default Network Action dropdown does not open in app settings.
  - Quick Settings don't apply in app settings.
  - Related: Add successful save action indicator when a setting is successfully saved.
    - There was an issue on GH about this - from @northys - but could not find it right now.
- Design (opinion)
  - Toggle switches feel small, may be hard to hit.
  - "Add Rule" bar is pretty dark and in your face.
  - Global Settings could also make use of the blue dots.
  - I still don't like the "Revert to default settings" text-button placement. I think it disrupts the flow.
  - Settings key in blue is too much in your face.

**Comment by ppacher** [comment]
Ok, I just checked the "technical" part because yesterday everything worked when I tested it so:

> Default Network Action dropdown does not open in app settings.

You need to "unlock" the setting first (as we had previously) with the button on the right. I guess we should show a "blocked" cursor on the dropdown and don't do hover effects as it's disabled.

> Quick Settings don't apply in app settings.

Same here, the setting needs to be unlocked first. Should we automatically "unlock" the setting if the user clicks on it or deny opening the quick-settings menu at all?

> Related: Add successful save action indicator when a setting is successfully saved.

I'd rather remove the complete auto-save feature and add a save button then. Showing success notifications with auto-save might spam the user with lots and lots of messages.

For the design things:

> Toggle switches feel small, may be hard to hit.

@LukeSeers 

> "Add Rule" bar is pretty dark and in your face.

I felt it's important that the user recognizes this as something "clickable"/primary for that setting. @LukeSeers 

> Global Settings could also make use of the blue dots.

I disabled that on purpose because you easily end up with every category being "blue" because you changed a single setting in that category (or manually set it to the default value - which is different than having it set to "system default")

> I still don't like the "Revert to default settings" text-button placement. I think it disrupts the flow.

Agree, any opinion on how to make it better? In the app settings, you can click the "lock" button on the right as well.

> Settings key in blue is too much in your face.

Just for devs and I wanted it to be easily visible while being relatively small.

**Comment by dhaavi** [comment]
Thanks for the clarifications, let's talk about it with @LukeSeers.

One more thing I also just noticed:
The blue dots only show on the sub-categories, which isn't a big problem in itself, as we only have two categories right now (Privacy Filter + SPN).
But, the SPN only has one setting, which means that you cannot even scroll down enough for the section to open and to see the blue dot. This means that you will never see the blue dot for the SPN section.

**Comment by northys** [comment]
morgen!

@dhaavi you mean this one? https://github.com/safing/portmaster-ui/issues/195

**Comment by dhaavi** [comment]
Guten Morgen @northys! ;)

Thanks for the pointer, but I couldn't find what I meant in the references issue.
I (vaguely) remember that you mentioned somewhere that you weren't sure if a setting was saved or not. And that you'd like to see a small message pop up in the bottom left, as is the case when an error occurs when changing a setting.

**Comment by northys** [comment]
@dhaavi yup at first Ive posted a bad issue but I xhanged the link after a minute or two... sorry. now the link points to correct one (about the saved popup notification)

**Comment by dhaavi** [comment]
More things when having a first glance together with @LukeSeers:

- Help texts are missing
- Restart (and other?) flags are missing
- Add some space on the bottom - currently page ends at the edge of last setting.
- Global/App setting source indicator does not work as expected - @LukeSeers.

**Comment by northys** [comment]
> * Settings key in blue is too much in your face.

and yes! blue is forbidden! i wanted the progress bar to be red/green and my request was denied! :D

**Comment by northys** [comment]
guys? is there any way to test changes like this one? i'm already subscribed to beta portmaster releases but i suppose that there don't include ui changes

**Comment by northys** [comment]
oh this log looks like i i have't run the cown command and that i'm stupid. okay :) i'll reserve more time tomorrow to spint this off.

**Comment by northys** [comment]
@dhaavi btw before it happens how can i correctly kill the stable ui from occupying  required ports?

**Review by dhaavi — APPROVED** [review]

**Comment by northys** [comment]
I love that I can go to simple on/off toggle config instead of network rating I've never used ♥️

**Comment by davegson** [comment]
thanks, so good to hear!

we believe this will have a big impact for new users too, as the easier toggles are now the default

**Pull request merged**
